# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the
# server process.


# SITE SETTINGS ---------------------------------------------------------------
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be
# accessible in the templates via {{ site.myvariable }}.

title: Language Development and Processing Lab
subtitle: University of Washington, Seattle &mdash; Department of Linguistics
email: ldplab@uw.edu
description: >- # this ignores newlines until the "baseurl" variable/setting
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

github_username: ldplab

baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
paper_url: /assets/papers
image_url: /assets/images

timezone: America/Los_Angeles

# build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include: 
  - '.htaccess'

# exclude from processing...
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/images/akira/
  - assets/images/hidden/
  - assets/images/unused/
  - hidden/
  - _posts/
  - _data/akira.yml
  - _config.yml
  - _config_dev.yml
  - _config_prod.yml
  - _config_stage.yml
  - dev.sh
  - prod.sh
  - stage.sh
  - todo.list
